theme: jekyll-theme-minimal
title: RomiBot - Política de Privacidade.
description: As políticas de privacidade acerca do bot de WhatsApp: RomiBot, criada por Sergio Ruiz, licenciando em informática educacional na Universidade Federal do Oeste do Pará.
